kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: portfolio
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.configs."localhost:5000".tls]
    insecure_skip_verify = true
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 6001
    protocol: TCP
  - containerPort: 443
    hostPort: 6000
    protocol: TCP