name: React CI Build

on:
  push:
    paths:
      - 'react/**'
      - '.github/workflows/react.yml'

jobs:
  Test-and-Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd react
          yarn install

      - name: Run tests
        run: |
          cd react
          yarn test:ci

      - name: Build react artifacts
        run: |
          cd react
          yarn build
